CREATE DATABASE DAIWAHERO; 

USE DAIWAHERO; 


CREATE TABLE IF NOT EXISTS CATEGORIA(
PK_CATEGORIA BIGINT NOT NULL AUTO_INCREMENT,
NOME  VARCHAR(100),
TG_STATUS TINYINT(1),
PRIMARY KEY (PK_CATEGORIA)
);

CREATE TABLE IF NOT EXISTS ESTOQUE(
PK_ESTOQUE BIGINT NOT NULL AUTO_INCREMENT,
QUANTIDADE INTEGER(30),
TG_STATUS TINYINT(1),
PRIMARY KEY (PK_ESTOQUE)
);

CREATE TABLE IF NOT EXISTS IMAGEM(
PK_IMAGEM BIGINT NOT NULL AUTO_INCREMENT,
IMAGEM_1 VARCHAR(150), 
IMAGEM_2 VARCHAR(150), 
IMAGEM_3 VARCHAR(150),
IMAGEM_4 VARCHAR(150),
PRIMARY KEY (PK_IMAGEM)
);

CREATE TABLE IF NOT EXISTS PRODUTO(
PK_PRODUTO BIGINT NOT NULL AUTO_INCREMENT,
NOME  VARCHAR(100),
VALOR VARCHAR(10),
DESCRICAO VARCHAR(150),
BREVEDESCRICAO VARCHAR(150),
STATUS TINYINT(1),
TG_STATUS TINYINT(1),
FK_CATEGORIA BIGINT(30),
FK_ESTOQUE BIGINT(30),
FK_IMAGEM BIGINT(30),
PRIMARY KEY (PK_PRODUTO),
FOREIGN KEY (FK_CATEGORIA) REFERENCES CATEGORIA (PK_CATEGORIA),
FOREIGN KEY (FK_ESTOQUE) REFERENCES ESTOQUE (PK_ESTOQUE),
FOREIGN KEY (FK_IMAGEM) REFERENCES IMAGEM (PK_IMAGEM)
);

